services:
  - type: web
    name: paladinHub-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

databases:
  - name: paladinhubdb
    databaseName: paladinhubdb
    plan: free