using Microsoft.AspNetCore.Mvc;
using PaladinProject.Models;
using TalentBuilder.Models;
using static System.Net.WebRequestMethods;

namespace PaladinProject.Controllers
{
	public class SpellbookController : Controller
	{
		public List<Spell> spellbook = new List<Spell>()
		{
			new Spell{Id = 1,  Name = "Divine Resonance",               Icon = "Divine Resonance.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=386738/divine-resonance"},
			new Spell{Id = 1,  Name = "Divine Glimpse",               Icon = "Divine Glimpse.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=387805/divine-glimpse"},
			new Spell{Id = 2,  Name = "Zealot's Paragon",              Icon = "Zealots Paragon.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=391142/zealots-paragon"},
			new Spell{Id = 3,  Name = "Improved Cleanse",              Icon = "Improved Cleanse.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=393024/improved-cleanse"},
			new Spell{Id = 4,  Name = "Penitence",                     Icon = "Penitence.jpg",                     Description = "spell", Irl = "https://www.wowhead.com/spell=403026/penitence"},
			new Spell{Id = 5,  Name = "Inquisitor's Ire",              Icon = "Inquisitor's Ire.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=403975/inquisitors-ire"},
			new Spell{Id = 6,  Name = "Ferren Marcus's Fervor",        Icon = "Ferren Marcus's Fervor.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=378762/ferren-marcuss-fervor"},
			new Spell{Id = 7,  Name = "Crusader's Resolve",            Icon = "Crusader's Resolve.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=380188/crusaders-resolve"},
			new Spell{Id = 8,  Name = "Commanding Light",              Icon = "Commanding Light.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=387781/commanding-light"},
			new Spell{Id = 9,  Name = "Inspiring Vanguard",            Icon = "Inspiring Vanguard.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=393022/inspiring-vanguard"},
			new Spell{Id = 10, Name = "Hand of Divinity",              Icon = "Hand of Divinity.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=414273/hand-of-divinity"},
			new Spell{Id = 11, Name = "Righteous Verdict",             Icon = "Final Verdict.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=267610/righteous-verdict"},
			new Spell{Id = 12, Name = "Improved Blessing of Protection",Icon = "Improved Blessing of Protection.jpg", Description = "spell", Irl = "https://www.wowhead.com/spell=384909/improved-blessing-of-protection"},
			new Spell{Id = 13, Name = "Breaking Dawn",                 Icon = "Breaking Dawn.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=409673/breaking-dawn"},
			new Spell{Id = 14, Name = "Veneration",                    Icon = "Veneration.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=392902/veneration"},
			new Spell{Id = 15, Name = "Touch of Light",                Icon = "Touch of Light.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=386922/touch-of-light"},
			new Spell{Id = 16, Name = "Golden Path",                   Icon = "Golden Path.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=386916/golden-path"},
			new Spell{Id = 17, Name = "Holy Aegis",                    Icon = "Holy Aegis.jpg",                     Description = "spell", Irl = "https://www.wowhead.com/spell=379008/holy-aegis"},
			new Spell{Id = 18, Name = "Infusion of Light",             Icon = "Infusion of Light.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=53576/infusion-of-light"},
			//2new Spell{Id = 19, Name = "Greater Judgment",              Icon = "Greater Judgment.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
			//new Spell{Id = 19, Name = "Blessed Champion",              Icon = "Blessed Champion.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
			//new Spell{Id = 19, Name = "Executioner's Will",              Icon = "Executioners Will.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
			//new Spell{Id = 19, Name = "Tower of Radiance",              Icon = "Executioners Will.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
			//new Spell{Id = 19, Name = "Holy Ritual",              Icon = "Holy Ritual.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
			new Spell{Id = 20, Name = "Moment of Compassion",          Icon = "Moment of Compassion.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=407236/moment-of-compassion"},
			new Spell{Id = 21, Name = "Searing Light",                 Icon = "Searing Light.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=403221/searing-light"},
			new Spell{Id = 22, Name = "Glistening Radiance",           Icon = "Glistening Radiance.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=409647/glistening-radiance"},
			new Spell{Id = 23, Name = "Blessed Focus",                 Icon = "Blessed Focus.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=414289/blessed-focus"},
			new Spell{Id = 24, Name = "Daybreak",                      Icon = "Daybreak.jpg",                        Description = "spell", Irl = "https://www.wowhead.com/spell=414293/daybreak"},
			new Spell{Id = 25, Name = "Barrier of Faith",              Icon = "Barrier of Faith.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
			new Spell{Id = 26, Name = "Holy Light",                    Icon = "Holy Light.jpg",                      Description = "spell", Irl = "https://www.wowhead.com/spell=82326/holy-light"},
			new Spell{Id = 27, Name = "Holy Shock",                    Icon = "Holy Shock.jpg",                      Description = "spell", Irl = "https://www.wowhead.com/spell=20473/holy-shock"},
			new Spell{Id = 28, Name = "Beacon of Virtue",              Icon = "Beacon of Virtue.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=200025/beacon-of-virtue"},
			new Spell{Id = 29, Name = "Beacon of Light",               Icon = "Beacon of Light.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=53563/beacon-of-light"},
			new Spell{Id = 30, Name = "Avenging Wrath",                Icon = "Avenging Wrath.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=31884/avenging-wrath"},
			new Spell{Id = 31,  Name = "Divine Inspiration",            Icon = "Divine Inspiration.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=432964/divine-inspiration"},
			new Spell{Id = 32,  Name = "Blessed Calling",               Icon = "Blessed Calling.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=469770/blessed-calling"},
			new Spell{Id = 33,  Name = "Blade of Wrath",                Icon = "Blade of Justice.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=231832/blade-of-wrath"},
			new Spell{Id = 34,  Name = "Focused Enmity",                Icon = "Focused Enmity.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=378845/focused-enmity"},
			new Spell{Id = 35,  Name = "Consecration in Flame",         Icon = "Consecration in Flame.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=379022/consecration-in-flame"},
			new Spell{Id = 36,  Name = "Seal of Charity",               Icon = "Seal of Charity.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=384815/seal-of-charity"},
			new Spell{Id = 37,  Name = "Strength in Adversity",         Icon = "Eye for an Eye.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=393071/strength-in-adversity"},
			new Spell{Id = 38,  Name = "Light's Conviction",            Icon = "Light's Conviction.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=414073/lights-conviction"},
			new Spell{Id = 39,  Name = "Seal of the Crusader",          Icon = "Seal of the Crusader.jpg",          Description = "spell", Irl = "https://www.wowhead.com/spell=416770/seal-of-the-crusader"},
			new Spell{Id = 40,  Name = "Sun Sear",                      Icon = "Sun Sear.jpg",                      Description = "spell", Irl = "https://www.wowhead.com/spell=431413/sun-sear"},
			new Spell{Id = 41,  Name = "Morning Star",                  Icon = "Morning Star.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=431482/morning-star"},
			new Spell{Id = 42,  Name = "Holy Reprieve",                 Icon = "Holy Reprieve.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=469445/holy-reprieve"},
			new Spell{Id = 43,  Name = "First Avenger",                 Icon = "First Avenger.jpg",                 Description = "Avenger's Shield hits 2 additional targets, and grants you an absorb shield for 100% of all damage it deals.", Irl = "https://www.wowhead.com/spell=203776/first-avenger"},
			new Spell{Id = 44,  Name = "Resplendent Light",             Icon = "Resplendent Light.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=392902/resplendent-light"},
			new Spell{Id = 45,  Name = "Boundless Salvation",           Icon = "Boundless Salvation.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=392951/boundless-salvation"},
			new Spell{Id = 46,  Name = "Light's Celerity",              Icon = "Light's Celerity.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=403698/lights-celerity"},
			new Spell{Id = 47,  Name = "Improved Holy Shield",          Icon = "Improved Holy Shield.jpg",          Description = "spell", Irl = "https://www.wowhead.com/spell=393030/improved-holy-shield"},
			new Spell{Id = 48,  Name = "Improved Ardent Defender",      Icon = "Improved Ardent Defender.jpg",      Description = "spell", Irl = "https://www.wowhead.com/spell=393114/improved-ardent-defender"},
			new Spell{Id = 49,  Name = "Liberation",                    Icon = "Liberation.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=461287/liberation"},
			new Spell{Id = 50,  Name = "Blade of Vengeance",            Icon = "Blade of Vengeance.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=403826/blade-of-vengeance"},
			new Spell{Id = 51,  Name = "Reclamation",                   Icon = "Reclamation.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=415364/reclamation"},
			new Spell{Id = 52,  Name = "Luminosity",                    Icon = "Luminosity.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=431402/luminosity"},
			new Spell{Id = 53,  Name = "Solar Grace",                   Icon = "Solar Grace.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=431404/solar-grace"},
			new Spell{Id = 54,  Name = "Tirion's Devotion",             Icon = "Tirion's Devotion.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=414720/tirions-devotion"},
			new Spell{Id = 55,  Name = "Faith's Armor",                 Icon = "Faith's Armor.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=406101/faiths-armor"},
			new Spell{Id = 56,  Name = "Judgment of Justice",           Icon = "Judgment of Justice.jpg",           Description = "Judgment deals 10% increased damage and increases your movement speed by 10% for 5 sec.\r\n\r\nIf you have Greater Judgment, Judgment slows enemies by 30% for 8 sec.", Irl = "https://www.wowhead.com/spell=403495/judgment-of-justice"},
			new Spell{Id = 57,  Name = "Shared Resolve",                Icon = "Shared Resolve.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=432821/shared-resolve"},
			new Spell{Id = 58,  Name = "Divine Reach",                  Icon = "Divine Reach.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=469476/divine-reach"},
			new Spell{Id = 59,  Name = "Rule of Law",                   Icon = "Rule of Law.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=214202/rule-of-law"},
			//new Spell{Id = 59,  Name = "Light's Guidance",                   Icon = "Rule of Law.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=214202/rule-of-law"},
			//new Spell{Id = 59,  Name = "Judge, Jury and Executioner",                   Icon = "Judge, Jury and Executioner.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=214202/rule-of-law"},
			new Spell{Id = 60,  Name = "Aurora",                        Icon = "Aurora.jpg",                        Description = "spell", Irl = "https://www.wowhead.com/spell=439760/aurora"},
			//new Spell{Id = 60,  Name = "Sacrosanct Crusade",                        Icon = "Sacrosanct Crusade.jpg",                        Description = "spell", Irl = "https://www.wowhead.com/spell=439760/aurora"},
			//new Spell{Id = 60,  Name = "Truth Prevails",                        Icon = "Truth Prevails.jpg",                        Description = "spell", Irl = "https://www.wowhead.com/spell=439760/aurora"},
			new Spell{Id = 61,  Name = "Light's Countenance",           Icon = "Light's Countenance.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=469325/lights-countenance"},
			new Spell{Id = 62,  Name = "Sacred Strength",               Icon = "Sacred Strength.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=469337/sacred-strength"},
			new Spell{Id = 63,  Name = "Divine Revelations",            Icon = "Divine Revelations.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=387808/divine-revelations"},
			new Spell{Id = 64,  Name = "Lightforged Blessing",          Icon = "Lightforged Blessing.jpg",          Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			new Spell{Id = 65,  Name = "Unwavering Spirit",             Icon = "Unwavering Spirit.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=392911/unwavering-spirit"},
			new Spell{Id = 66,  Name = "Beacon of the Lightbringer",    Icon = "Lightbearer.jpg",    Description = "spell", Irl = "https://www.wowhead.com/spell=197446/beacon-of-the-lightbringer"},
			new Spell{Id = 67,  Name = "Beacon of Faith",               Icon = "Beacon of Faith.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=156910/beacon-of-faith"},
			new Spell{Id = 68,  Name = "Blessing of Summer",            Icon = "Blessing of Summer.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=388007/blessing-of-summer"},
			new Spell{Id = 69,  Name = "Blessing of Spring",            Icon = "Blessing of Spring.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=388013/blessing-of-spring"},
			new Spell{Id = 70,  Name = "Blessing of Autumn",            Icon = "Blessing of Autumn.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=388010/blessing-of-autumn"},
			new Spell{Id = 71,  Name = "Blessing of Winter",            Icon = "Blessing of Winter.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=388011/blessing-of-winter"},
			new Spell{Id = 72,  Name = "Glorious Dawn",                 Icon = "Glorious Dawn.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=414387/glorious-dawn"},
			new Spell{Id = 73,  Name = "Light of the Titans",           Icon = "Light of Dawn.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=378762/light-of-the-titans"},
			new Spell{Id = 74,  Name = "Empyrean Legacy",               Icon = "Empyrean Legacy.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=387998/empyrean-legacy"},
			new Spell{Id = 75,  Name = "Moment of Compassion",          Icon = "Moment of Compassion.jpg",          Description = "spell", Irl = "https://www.wowhead.com/spell=407236/moment-of-compassion"},
			new Spell{Id = 76,  Name = "Searing Light",                 Icon = "Searing Light.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=403221/searing-light"},
			new Spell{Id = 77,  Name = "Glistening Radiance",           Icon = "Glistening Radiance.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=409647/glistening-radiance"},
			new Spell{Id = 78,  Name = "Blessed Focus",                 Icon = "Blessed Focus.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=414289/blessed-focus"},
			new Spell{Id = 79,  Name = "Daybreak",                      Icon = "Daybreak.jpg",                      Description = "spell", Irl = "https://www.wowhead.com/spell=414293/daybreak"},
			new Spell{Id = 80,  Name = "Barrier of Faith",              Icon = "Barrier of Faith.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
			//new Spell{Id = 80,  Name = "Barricade  of Faith",              Icon = "Barrier of Faith.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
			//new Spell{Id = 80,  Name = "Rush of Light",              Icon = "Rush of Light.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
			//new Spell{Id = 80,  Name = "Resolute Defender",              Icon = "Veneration.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
			//new Spell{Id = 80,  Name = "Obduracy",              Icon = "Obduracy.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
			new Spell{Id = 81,  Name = "Holy Light",                    Icon = "Holy Light.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=82326/holy-light"},
			new Spell{Id = 82,  Name = "Holy Shock",                    Icon = "Holy Shock.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=20473/holy-shock"},
			new Spell{Id = 83,  Name = "Beacon of Virtue",              Icon = "Beacon of Virtue.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=200025/beacon-of-virtue"},
			new Spell{Id = 84,  Name = "Beacon of Light",               Icon = "Beacon of Light.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=53563/beacon-of-light"},
			new Spell{Id = 85,  Name = "Avenging Wrath",                Icon = "Avenging Wrath.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=31884/avenging-wrath"},
			new Spell{Id = 86,  Name = "Infusion of Light",             Icon = "Infusion of Light.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=53576/infusion-of-light"},
			new Spell{Id = 87,  Name = "Greater Judgment",              Icon = "Greater Judgment.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
			new Spell{Id = 88,  Name = "Light's Hammer",                Icon = "Lights Hammer.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=114158/lights-hammer"},
			new Spell{Id = 89,  Name = "Holy Prism",                    Icon = "Holy Prism.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=114165/holy-prism"},
			new Spell{Id = 90,  Name = "Divine Toll",                   Icon = "Divine Toll.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=375576/divine-toll"},
			new Spell{Id = 91,  Name = "Tyr's Deliverance",             Icon = "Tyr's Deliverance.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=200652/tyrs-deliverance"},
			new Spell{Id = 92,  Name = "Light of the Martyr",           Icon = "Light of the Martyr.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=183998/light-of-the-martyr"},
			new Spell{Id = 93,  Name = "Light of Dawn",                 Icon = "Light of Dawn.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=85222/light-of-dawn"},
			new Spell{Id = 94,  Name = "Judgment",                      Icon = "Judgment.jpg",                      Description = "spell", Irl = "https://www.wowhead.com/spell=20271/judgment"},
			new Spell{Id = 95,  Name = "Crusader Strike",               Icon = "Crusader Strike.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=35395/crusader-strike"},
			new Spell{Id = 96,  Name = "Flash of Light",                Icon = "Flash of Light.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=19750/flash-of-light"},
			new Spell{Id = 97,  Name = "Holy Radiance",                 Icon = "Holy Radiance.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=82327/holy-radiance"},
			new Spell{Id = 98,  Name = "Lay on Hands",                  Icon = "Lay on Hands.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=633/lay-on-hands"},
			//new Spell{Id = 98,  Name = "Empyreal Ward",                  Icon = "Lay on Hands.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=633/lay-on-hands"},
			new Spell{Id = 99,  Name = "Divine Protection",             Icon = "Divine Protection.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=498/divine-protection"},
			new Spell{Id = 100, Name = "Ardent Defender",               Icon = "Ardent Defender.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=31850/ardent-defender"},
			new Spell{Id = 101, Name = "Divine Shield",                 Icon = "Divine Shield.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=642/divine-shield"},
			new Spell{Id = 102, Name = "Cleanse",                       Icon = "Cleanse.jpg",                       Description = "spell", Irl = "https://www.wowhead.com/spell=4987/cleanse"},
			new Spell{Id = 103, Name = "Blessing of Protection",        Icon = "Blessing of Protection.jpg",        Description = "spell", Irl = "https://www.wowhead.com/spell=1022/blessing-of-protection"},
			new Spell{Id = 104, Name = "Blessing of Freedom",           Icon = "Blessing of Freedom.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=1044/blessing-of-freedom"},
			new Spell{Id = 105, Name = "Blessing of Sacrifice",         Icon = "Blessing of Sacrifice.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=6940/blessing-of-sacrifice"},
			new Spell{Id = 106, Name = "Blessing of Spellwarding",      Icon = "Blessing of Spellwarding.jpg",      Description = "spell", Irl = "https://www.wowhead.com/spell=204018/blessing-of-spellwarding"},
			new Spell{Id = 107, Name = "Rebuke",                        Icon = "Rebuke.jpg",                        Description = "spell", Irl = "https://www.wowhead.com/spell=96231/rebuke"},
			new Spell{Id = 108, Name = "Divine Steed",                  Icon = "Divine Steed.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
			new Spell{Id = 109, Name = "Hammer of Justice",             Icon = "Hammer of Justice.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=853/hammer-of-justice"},
			new Spell{Id = 110, Name = "Hammer of Wrath",               Icon = "Hammer of Wrath.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=24275/hammer-of-wrath"},
			new Spell{Id = 111, Name = "Shield of the Righteous",       Icon = "Shield of the Righteous.jpg",       Description = "spell", Irl = "https://www.wowhead.com/spell=53600/shield-of-the-righteous"},
			new Spell{Id = 112, Name = "Judgment of Light",             Icon = "Judgment of Light.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=183778/judgment-of-light"},
			new Spell{Id = 113, Name = "Consecration",                  Icon = "Consecration.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=26573/consecration"},
			new Spell{Id = 114, Name = "Bastion of Light",              Icon = "Bastion of Light.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=378974/bastion-of-light"},
			new Spell{Id = 115, Name = "Sanctified Wrath",              Icon = "Sanctified Wrath.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=53376/sanctified-wrath"},
			new Spell{Id = 116, Name = "Unbreakable Spirit",            Icon = "Unbreakable Spirit.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=114154/unbreakable-spirit"},
			new Spell{Id = 117, Name = "Hand of the Protector",         Icon = "Power of the Silver Hand.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=315341/hand-of-the-protector"},
			new Spell{Id = 118, Name = "Final Stand",                   Icon = "Final Stand.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=204077/final-stand"},
			new Spell{Id = 118, Name = "Eye of Tyr",                   Icon = "Eye of Tyr.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Light's Deliverance",                   Icon = "Lights Deliverance.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Turn Evil",                   Icon = "Turn Evil.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Sentinel",                   Icon = "Sentinel.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Awakening",                   Icon = "Awakening.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//2new Spell{Id = 118, Name = "Awakening",                   Icon = "Awakening.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Blessing of An'she",                   Icon = "Blessing of Anshe.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Divine Guidance",                   Icon = "Divine Guidance.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Holy Flames",                   Icon = "Holy Flames.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Cleanse Toxins",                   Icon = "Cleanse Toxins.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Unbound Freedom",                   Icon = "Blessing of Freedom.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Lightbearer",                   Icon = "Lightbearer.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Healing Hands",                   Icon = "Healing Hands.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			//new Spell{Id = 118, Name = "Faith in the Light",                   Icon = "Faith in the Light.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
			new Spell{Id = 119, Name = "Guardian of Ancient Kings",     Icon = "Guardian of Ancient Kings.jpg",     Description = "spell", Irl = "https://www.wowhead.com/spell=86659/guardian-of-ancient-kings"},
			new Spell{Id = 120, Name = "Avenger's Shield",              Icon = "Avengers Shield.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=31935/avengers-shield"},
			new Spell{Id = 121, Name = "Shining Light",                 Icon = "Shining Light.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=327510/shining-light"},
			new Spell{Id = 122, Name = "Redoubt",                       Icon = "Redoubt.jpg",                       Description = "spell", Irl = "https://www.wowhead.com/spell=280373/redoubt"},
			new Spell{Id = 123, Name = "Grand Crusader",                Icon = "Grand Crusader.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=85043/grand-crusader"},
			new Spell{Id = 124, Name = "Holy Shield",                   Icon = "Holy Shield.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=152261/holy-shield"},
			new Spell{Id = 125, Name = "Bulwark of Order",              Icon = "Bulwark of Order.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=209389/bulwark-of-order"},
			new Spell{Id = 126, Name = "Judgment of the Light",         Icon = "Judgment of the Light.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=183778/judgment-of-the-light"},
			new Spell{Id = 127, Name = "Light of the Protector",        Icon = "Light of the Protector.jpg",        Description = "spell", Irl = "https://www.wowhead.com/spell=184092/light-of-the-protector"},
			new Spell{Id = 128, Name = "Consecrated Ground",            Icon = "Consecrated Ground.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=204054/consecrated-ground"},
			new Spell{Id = 129, Name = "Crusader's Judgment",           Icon = "Crusaders Judgment.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=204023/crusaders-judgment"},
			new Spell{Id = 130, Name = "Final Verdict",                 Icon = "Final Verdict.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=383328/final-verdict"},
			new Spell{Id = 131, Name = "Execution Sentence",            Icon = "Execution Sentence.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=343527/execution-sentence"},
			new Spell{Id = 132, Name = "Blade of Justice",              Icon = "Blade of Justice.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=184575/blade-of-justice"},
			new Spell{Id = 133, Name = "Templar's Verdict",             Icon = "Templar's Verdict.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=85256/templars-verdict"},
			new Spell{Id = 134, Name = "Justicar's Vengeance",          Icon = "Justicars Vengeance.jpg",          Description = "spell", Irl = "https://www.wowhead.com/spell=215661/justicars-vengeance"},
			new Spell{Id = 135, Name = "Divine Storm",                  Icon = "Divine Storm.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=53385/divine-storm"},
			new Spell{Id = 136, Name = "Crusade",                       Icon = "Crusade.jpg",                       Description = "spell", Irl = "https://www.wowhead.com/spell=231895/crusade"},
			new Spell{Id = 137, Name = "Seraphim",                      Icon = "Seraphim.jpg",                      Description = "spell", Irl = "https://www.wowhead.com/spell=152262/seraphim"},
			new Spell{Id = 138, Name = "Wake of Ashes",                 Icon = "Wake of Ashes.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=255937/wake-of-ashes"},
			new Spell{Id = 139, Name = "Hammer of Wrath",               Icon = "Hammer of Wrath.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=24275/hammer-of-wrath"},
			//2new Spell{Id = 140, Name = "Blade of Vengeance",            Icon = "Blade of Justice.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=403826/blade-of-vengeance"},
			new Spell{Id = 141, Name = "Vanguard's Momentum",           Icon = "Vanguard's Momentum.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=405065/vanguards-momentum"},
			new Spell{Id = 142, Name = "Adjudication",                  Icon = "Adjudication.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=405541/adjudication"},
			new Spell{Id = 143, Name = "Templar Strikes",               Icon = "Templar Strikes.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=407480/templar-strikes"},
			new Spell{Id = 144, Name = "Holy Blade",                    Icon = "Holy Blade.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=406158/holy-blade"},
			new Spell{Id = 145, Name = "Truth's Wake",                  Icon = "Truth's Wake.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=406154/truths-wake"},
			new Spell{Id = 146, Name = "Burning Crusade",               Icon = "Burning Crusade.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=406545/burning-crusade"},
			new Spell{Id = 147, Name = "Burning Vengeance",             Icon = "Burning Vengeance.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=406646/burning-vengeance"},
			new Spell{Id = 148, Name = "Searing Judgment",              Icon = "Searing Judgment.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=403530/searing-judgment"},
			new Spell{Id = 149, Name = "Vengeful Wrath",                Icon = "Hammer of Wrath.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=403592/vengeful-wrath"},
			new Spell{Id = 150, Name = "Radiant Glory",                 Icon = "Radiant Glory.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=405757/radiant-glory"},
			new Spell{Id = 151, Name = "Lightbringer's Radiance",       Icon = "Lightbringer's Radiance.jpg",       Description = "spell", Irl = "https://www.wowhead.com/spell=405767/lightbringers-radiance"},
			new Spell{Id = 152, Name = "Divine Arbiter",                Icon = "Divine Arbiter.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=406251/divine-arbiter"},
			new Spell{Id = 153, Name = "Seal of Wrath",                 Icon = "Seal of Wrath.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=405798/seal-of-wrath"},
			new Spell{Id = 154, Name = "Crusader's Reprieve",           Icon = "Crusader's Reprieve.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=403010/crusaders-reprieve"},
			new Spell{Id = 155, Name = "Zeal",                          Icon = "Zeal.jpg",                          Description = "spell", Irl = "https://www.wowhead.com/spell=269569/zeal"},
			//new Spell{Id = 155, Name = "Zealous Vindication",                          Icon = "Zealous Vindication.jpg",                          Description = "spell", Irl = "https://www.wowhead.com/spell=269569/zeal"},
			new Spell{Id = 156, Name = "Expurgation",                   Icon = "Expurgation.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=383344/expurgation"},
			new Spell{Id = 157, Name = "Righteous Cause",               Icon = "Righteous Cause.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=405686/righteous-cause"},
			new Spell{Id = 158, Name = "Divine Purpose",                Icon = "Divine Purpose.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=223819/divine-purpose"},
			new Spell{Id = 159, Name = "Empyrean Power",                Icon = "Empyrean Power.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=286392/empyrean-power"},
			new Spell{Id = 160, Name = "Ashes to Ashes",                Icon = "Ashes to Ashes.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=405607/ashes-to-ashes"},
			new Spell{Id = 161, Name = "Highlord's Judgment",           Icon = "Highlord's Judgment.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=405757/highlords-judgment"},
			new Spell{Id = 162, Name = "Templar Slash",                 Icon = "Templar Slash.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=407479/templar-slash"},
			new Spell{Id = 163, Name = "Templar Strike",                Icon = "Templar Strike.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=407480/templar-strike"},
			//2new Spell{Id = 164, Name = "Divine Resonance",              Icon = "Divine Resonance.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=384027/divine-resonance"},
			new Spell{Id = 165, Name = "Vanguard's Momentum",           Icon = "Vanguard's Momentum.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=405065/vanguards-momentum"},
			new Spell{Id = 166, Name = "Truth's Wake",                  Icon = "Truth's Wake.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=406154/truths-wake"},
			new Spell{Id = 167, Name = "Crusader's Resolve",            Icon = "Crusader's Resolve.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=380188/crusaders-resolve"},
			new Spell{Id = 168, Name = "Divine Wrath",                  Icon = "Divine Wrath.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=406872/divine-wrath"},
			new Spell{Id = 169, Name = "Divine Call",                   Icon = "Divine Call.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=403566/divine-call"},
			new Spell{Id = 170, Name = "Seal of Order",                 Icon = "Seal of Order.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=385425/seal-of-order"},
			new Spell{Id = 171, Name = "Seal of Might",                 Icon = "Seal of Might.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=385450/seal-of-might"},
			new Spell{Id = 172, Name = "Seal of Mercy",                 Icon = "Seal of Mercy.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=385427/seal-of-mercy"},
			new Spell{Id = 173, Name = "Seal of Clarity",               Icon = "Seal of Clarity.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=385428/seal-of-clarity"},
			new Spell{Id = 174, Name = "Seal of the Crusader",          Icon = "Seal of the Crusader.jpg",          Description = "spell", Irl = "https://www.wowhead.com/spell=416770/seal-of-the-crusader"},
			new Spell{Id = 175, Name = "Tyr's Enforcer",                Icon = "Tyr's Enforcer.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=406570/tyrs-enforcer"},
			new Spell{Id = 176, Name = "Relentless Inquisitor",         Icon = "Relentless Inquisitor.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=376996/relentless-inquisitor"},
			new Spell{Id = 177, Name = "Of Dusk and Dawn",              Icon = "Light of Dawn.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=385125/of-dusk-and-dawn"},
			new Spell{Id = 178, Name = "Divine Purpose (Retribution)",  Icon = "Divine Purpose (Retribution).jpg",  Description = "spell", Irl = "https://www.wowhead.com/spell=223819/divine-purpose"},
			new Spell{Id = 179, Name = "Sanctified Plates",             Icon = "Sanctified Plates.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=394081/sanctified-plates"},
			new Spell{Id = 180, Name = "Incandescence",                 Icon = "Incandescence.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=385639/incandescence"},
			new Spell{Id = 181, Name = "Sealed Verdict",                Icon = "Sealed Verdict.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=385633/sealed-verdict"},
			//2new Spell{Id = 182, Name = "Divine Judgement",              Icon = "Divine Judgement.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=384820/divine-judgement"},
			//2new Spell{Id = 182, Name = "Undisputed Ruling",              Icon = "Greater Judgement.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=384820/divine-judgement"},
			//2new Spell{Id = 182, Name = "Stoicism",              Icon = "Stoicism.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=384820/divine-judgement"},
			//2new Spell{Id = 182, Name = "Seething Flames",              Icon = "Seething Flames.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=384820/divine-judgement"},
			//2new Spell{Id = 182, Name = "Sacrifice of the Just",              Icon = "Blessing of Sacrifice.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=384820/divine-judgement"},
			new Spell{Id = 183, Name = "Highlord's Wrath",              Icon = "Highlord's Wrath.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=405779/highlords-wrath"},
			new Spell{Id = 184, Name = "Aegis of Protection",           Icon = "Aegis of Protection.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=385515/aegis-of-protection"},
			new Spell{Id = 185, Name = "Aegis of Light",                Icon = "Aegis of Light.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=204150/aegis-of-light"},
			new Spell{Id = 186, Name = "Bulwark of Righteous Fury",     Icon = "Bulwark of Righteous Fury.jpg",     Description = "spell", Irl = "https://www.wowhead.com/spell=385422/bulwark-of-righteous-fury"},
			new Spell{Id = 187, Name = "Gift of the Golden Val'kyr",    Icon = "Gift of the Golden Valkyr.jpg",    Description = "spell", Irl = "https://www.wowhead.com/spell=407311/gift-of-the-golden-valkyr"},
			new Spell{Id = 188, Name = "Faith's Reward",                Icon = "Faith's Reward.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=385349/faiths-reward"},
			new Spell{Id = 189, Name = "Recompense",                    Icon = "Recompense.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=385427/recompense"},
			new Spell{Id = 190, Name = "Divine Allegiance",             Icon = "Divine Allegiance.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=406788/divine-allegiance"},
			new Spell{Id = 191, Name = "Resplendent Light (Ret)",       Icon = "Resplendent Light (Ret).jpg",       Description = "spell", Irl = "https://www.wowhead.com/spell=383254/resplendent-light"},
			new Spell{Id = 192, Name = "Shielding Words",               Icon = "Shielding Words.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=379010/shielding-words"},
			new Spell{Id = 193, Name = "Golden Path (Prot)",            Icon = "Golden Path (Prot).jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=386916/golden-path"},
			new Spell{Id = 194, Name = "Unending Light",                Icon = "Unending Light.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=405719/unending-light"},
			new Spell{Id = 195, Name = "Merciful Auras",                Icon = "Merciful Auras.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=385414/merciful-auras"},
			new Spell{Id = 196, Name = "Sanctified Ground (Ret)",       Icon = "Sanctified Ground (Ret).jpg",       Description = "spell", Irl = "https://www.wowhead.com/spell=204054/sanctified-ground"},
			new Spell{Id = 197, Name = "Punishment",                    Icon = "Rebuke.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=403537/punishment"},
			new Spell{Id = 198, Name = "Improved Cleanse (Ret)",        Icon = "Improved Cleanse (Ret).jpg",        Description = "spell", Irl = "https://www.wowhead.com/spell=393024/improved-cleanse"},
			new Spell{Id = 199, Name = "Seal of Mercy (Ret)",           Icon = "Seal of Mercy (Ret).jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=385427/seal-of-mercy"},
			new Spell{Id = 200, Name = "Avenging Wrath",                Icon = "Avenging Wrath.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=31884/avenging-wrath"},
			new Spell{Id = 201, Name = "Repentance",                    Icon = "Repentance.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=20066/repentance"},
			new Spell{Id = 202, Name = "Crusade",                       Icon = "Crusade.jpg",                       Description = "spell", Irl = "https://www.wowhead.com/spell=231895/crusade"},
			new Spell{Id = 203, Name = "Lay on Hands",                  Icon = "Lay on Hands.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=633/lay-on-hands"},
			new Spell{Id = 204, Name = "Blessing of Freedom",           Icon = "Blessing of Freedom.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=1044/blessing-of-freedom"},
			new Spell{Id = 205, Name = "Blessing of Sacrifice",         Icon = "Blessing of Sacrifice.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=6940/blessing-of-sacrifice"},
			new Spell{Id = 206, Name = "Shield of Vengeance",           Icon = "Shield of Vengeance.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=184662/shield-of-vengeance"},
			new Spell{Id = 207, Name = "Guardian of Ancient Kings",     Icon = "Guardian of Ancient Kings.jpg",     Description = "spell", Irl = "https://www.wowhead.com/spell=86659/guardian-of-ancient-kings"},
			new Spell{Id = 208, Name = "Holy Shock",                    Icon = "Holy Shock.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=20473/holy-shock"},
			new Spell{Id = 209, Name = "Beacon of Virtue",              Icon = "Beacon of Virtue.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=200025/beacon-of-virtue"},
			new Spell{Id = 210, Name = "Ardent Defender",               Icon = "Ardent Defender.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=31850/ardent-defender"},
			new Spell{Id = 211, Name = "Hammer of Wrath",               Icon = "Hammer of Wrath.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=24275/hammer-of-wrath"},
			new Spell{Id = 212, Name = "Tyr's Deliverance",             Icon = "Tyrs Deliverance.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=200652/tyrs-deliverance"},
			new Spell{Id = 213, Name = "Execution Sentence",            Icon = "Execution Sentence.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=343527/execution-sentence"},
			new Spell{Id = 214, Name = "Avenging Crusader",             Icon = "Avenging Crusader.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=216331/avenging-crusader"},
			new Spell{Id = 215, Name = "Divine Steed",                  Icon = "Divine Steed.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
			//new Spell{Id = 215, Name = "Cavalier",                  Icon = "Divine Steed.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
			//new Spell{Id = 215, Name = "Divine Spurs",                  Icon = "Divine Spurs.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
			//new Spell{Id = 215, Name = "Righteous Judgment",                  Icon = "Shake the Heavens.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
			//new Spell{Id = 215, Name = "Blades of Light",                  Icon = "Blades of Light.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
			//new Spell{Id = 215, Name = "Awestruck",                  Icon = "Awestruck.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
			//new Spell{Id = 215, Name = "Fires of Justice",                  Icon = "Fires of Justice.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
			//new Spell{Id = 215, Name = "Blessed Assurance",            Icon = "Merciful Auras.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
			//new Spell{Id = 215, Name = "Focused Enmity",            Icon = "Divine Inspiration.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
			new Spell{Id = 216, Name = "Aura Mastery",                  Icon = "Aura Mastery.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=31821/aura-mastery"},
			new Spell{Id = 217, Name = "Divine Hammer",                 Icon = "Divine Hammer.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=198034/divine-hammer"},
			new Spell{Id = 218, Name = "Final Reckoning",               Icon = "Final Reckoning.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=343721/final-reckoning"},
			new Spell{Id = 219, Name = "Bestow Faith",                  Icon = "Bestow Faith.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=223306/bestow-faith"},
			new Spell{Id = 220, Name = "Light of Dawn",                 Icon = "Light of Dawn.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=85222/light-of-dawn"},
			new Spell{Id = 221, Name = "Fist of Justice",               Icon = "Fist of Justice.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=234299/fist-of-justice"},
			new Spell{Id = 222, Name = "Eternal Flame",                 Icon = "Eternal Flame.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=114163/eternal-flame"},
			new Spell{Id = 223, Name = "Divine Toll",                   Icon = "Divine Toll.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=375576/divine-toll"},
			new Spell{Id = 224, Name = "Wake of Ashes",                 Icon = "Wake of Ashes.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=255937/wake-of-ashes"},
			////new Spell{Id = 225, Name = "Avenger's Shield",              Icon = "Avengers Shield.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=31935/avengers-shield"},
			new Spell{Id = 226, Name = "Rebuke",                        Icon = "Rebuke.jpg",                        Description = "spell", Irl = "https://www.wowhead.com/spell=96231/rebuke"},
			new Spell{Id = 227, Name = "Blade of Justice",              Icon = "Blade of Justice.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=184575/blade-of-justice"},
			new Spell{Id = 228, Name = "Power of the Silver Hand",      Icon = "Power of the Silver Hand.jpg",      Description = "spell", Irl = "https://www.wowhead.com/spell=200294/power-of-the-silver-hand"},
			new Spell{Id = 229, Name = "Blessing of Spellwarding",      Icon = "Blessing of Spellwarding.jpg",      Description = "spell", Irl = "https://www.wowhead.com/spell=204018/blessing-of-spellwarding"},
			new Spell{Id = 230, Name = "Divine Storm",                  Icon = "Divine Storm.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=53385/divine-storm"},
			new Spell{Id = 231, Name = "Shake the Heavens",             Icon = "Shake the Heavens.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=403509/shake-the-heavens"},
			new Spell{Id = 232, Name = "Blessed Hammer",                Icon = "Blessed Hammer.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=204019/blessed-hammer"},
			new Spell{Id = 233, Name = "Divine Purpose",                Icon = "Divine Purpose.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=223819/divine-purpose"},
			new Spell{Id = 234, Name = "Empyrean Legacy",              Icon = "Empyrean Legacy.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=387998/empyrean-legacy"},
			new Spell{Id = 235, Name = "Blessing of Summer",           Icon = "Blessing of Summer.jpg",           Description = "spell", Irl = "https://www.wowhead.com/spell=388007/blessing-of-summer"},
			new Spell{Id = 236, Name = "Radiant Glory",                Icon = "Radiant Glory.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=405757/radiant-glory"},
			new Spell{Id = 237, Name = "Lightforged Blessing",         Icon = "Lightforged Blessing.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Rising Sunlight",         Icon = "Rising Sunlight.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Righteous Protector",         Icon = "Shield of Vengeance.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Light's Revocation",         Icon = "Divine Shield.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Hammerfall",         Icon = "Crusaders Judgment.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Inflorescence of the Sunwell",         Icon = "Inflorescence of the Sunwell.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Burn to Ash",         Icon = "Burn to Ash.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Crusader's Might",         Icon = "Crusaders Might.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Wrathful Descent",         Icon = "Wrathful Descent.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Sun's Avatar",         Icon = "Suns Avatar.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Selfless Healer",         Icon = "Selfless Healer.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Rite of Sanctification",         Icon = "Rite of Sanctification.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Moment of Glory",         Icon = "Moment of Glory.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Unrelenting Charger",         Icon = "Unrelenting Charger.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			//new Spell{Id = 237, Name = "Hammer and Anvil",         Icon = "Hammer and Anvil.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
			new Spell{Id = 238, Name = "Dawnlight",                    Icon = "Dawnlight.jpg",                    Description = "spell", Irl = "https://www.wowhead.com/spell=431377/dawnlight"},
			new Spell{Id = 239, Name = "Eye for an Eye",               Icon = "Eye for an Eye.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=205191/eye-for-an-eye"},
			new Spell{Id = 239, Name = "Eye for an Eye",               Icon = "Divine Arbiter.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=205191/eye-for-an-eye"},
			new Spell{Id = 240, Name = "Holy Bulwark",                 Icon = "Holy Bulwark.jpg",                 Description = "spell", Irl = "https://www.wowhead.com/spell=432459/holy-bulwark"},
			new Spell{Id = 241, Name = "Crusading Strikes",            Icon = "Crusading Strikes.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=404542/crusading-strikes"},
			new Spell{Id = 242, Name = "Holy Shield",                  Icon = "Holy Shield.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=152261/holy-shield"},
			new Spell{Id = 243, Name = "Blinding Light",               Icon = "Blinding Light.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=115750/blinding-light"},
			new Spell{Id = 244, Name = "Expurgation",                  Icon = "Expurgation.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=383344/expurgation"},
			//new Spell{Id = 245, Name = "Shining Light",			  Icon = "Shining Light.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=321136/shining-light"},
			//new Spell{Id = 245, Name = "Holy Avenger",                Icon = "Suns Avatar.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=321136/shining-light"},
			//new Spell{Id = 245, Name = "Saved by the Light",                Icon = ".jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=321136/shining-light"},
			//new Spell{Id = 245, Name = "Lead the Charge",                Icon = "Lead the Charge.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=321136/shining-light"},
			new Spell{Id = 246, Name = "Final Verdict",                Icon = "Final Verdict.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=383328/final-verdict"},
			//new Spell{Id = 246, Name = "Blessing of the Forge",                Icon = "Final Verdict.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=383328/final-verdict"},
			new Spell{Id = 247, Name = "Hammer of the Righteous",      Icon = "Hammer of the Righteous.jpg",      Description = "spell", Irl = "https://www.wowhead.com/spell=53595/hammer-of-the-righteous"},
			//new Spell{Id = 247, Name = "For Whom the Bell Tolls",      Icon = "Hammer of the Righteous.jpg",      Description = "Divine Toll grants up to 100% increased damage to your next 3 Judgment when striking only 1 enemy. This amount is reduced by 20% for each additional target struck.", Irl = "https://www.wowhead.com/spell=53595/hammer-of-the-righteous"},
			new Spell{Id = 248, Name = "Barrier of Faith",             Icon = "Barrier of Faith.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
			new Spell{Id = 249, Name = "Overflowing Light",            Icon = "Overflowing Light.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=461244/overflowing-light"},
			new Spell{Id = 250, Name = "Glistening Radiance",          Icon = "Glistening Radiance.jpg",          Description = "spell", Irl = "https://www.wowhead.com/spell=461245/glistening-radiance"},
			new Spell{Id = 251, Name = "Vanguard's Momentum",          Icon = "Vanguard's Momentum.jpg",          Description = "spell", Irl = "https://www.wowhead.com/spell=405065/vanguards-momentum"},
			new Spell{Id = 252, Name = "Light's Celerity",             Icon = "Light's Celerity.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=403698/lights-celerity"},
			new Spell{Id = 253, Name = "Searing Light",                Icon = "Searing Light.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=403221/searing-light"},
			new Spell{Id = 254, Name = "Tyr's Enforcer",               Icon = "Tyr's Enforcer.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=406570/tyrs-enforcer"},
			new Spell{Id = 255, Name = "Boundless Salvation",          Icon = "Boundless Salvation.jpg",          Description = "spell", Irl = "https://www.wowhead.com/spell=392951/boundless-salvation"},
			new Spell{Id = 256, Name = "Daybreak",                     Icon = "Daybreak.jpg",                     Description = "spell", Irl = "https://www.wowhead.com/spell=414293/daybreak"},
			new Spell{Id = 257, Name = "Blessed Focus",                Icon = "Blessed Focus.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=414289/blessed-focus"},
			new Spell{Id = 258, Name = "Glimmer of Light",             Icon = "Shining Light.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=287269/glimmer-of-light"},
			new Spell{Id = 259, Name = "Resplendent Light",            Icon = "Resplendent Light.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=392902/resplendent-light"},
			new Spell{Id = 260, Name = "Holy Prism",                   Icon = "Holy Prism.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=114165/holy-prism"},
			new Spell{Id = 261, Name = "Divine Revelation",            Icon = "Divine Revelation.jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=387808/divine-revelations"},
			new Spell{Id = 262, Name = "Blessed Hands",                Icon = "Blessed Hands.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=379391/blessed-hands"},
			new Spell{Id = 263, Name = "Veneration",                   Icon = "Veneration.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=392902/veneration"},
			new Spell{Id = 264, Name = "Reclamation",                  Icon = "Rule of Law.jpg",                  Description = "Holy Shock and Crusader Strike refund up to 10% of their Mana cost and deal up to 50% more healing or damage, based on the target's missing health.", Irl = "https://www.wowhead.com/spell=415364/reclamation"},
			new Spell{Id = 265, Name = "Seal of Mercy",                Icon = "Seal of Mercy.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=385427/seal-of-mercy"},
			new Spell{Id = 266, Name = "Seal of Clarity",              Icon = "Seal of Clarity.jpg",              Description = "spell", Irl = "https://www.wowhead.com/spell=385428/seal-of-clarity"},
			new Spell{Id = 267, Name = "Seal of Might",                Icon = "Seal of Might.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=385450/seal-of-might"},
			new Spell{Id = 268, Name = "Seal of Order",                Icon = "Seal of Order.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=385425/seal-of-order"},
			new Spell{Id = 269, Name = "Tyr's Deliverance (PvP)",      Icon = "Tyr's Deliverance (PvP).jpg",      Description = "spell", Irl = "https://www.wowhead.com/spell=199454/tyrs-deliverance"},
			new Spell{Id = 270, Name = "Unending Light",               Icon = "Unending Light.jpg",               Description = "spell", Irl = "https://www.wowhead.com/spell=405719/unending-light"},
			new Spell{Id = 271, Name = "Afterimage",                   Icon = "Moment of Glory.jpg",                   Description = "spell", Irl = "https://www.wowhead.com/spell=385414/afterimage"},
			new Spell{Id = 272, Name = "Sanctified Wrath",             Icon = "Sanctified Wrath.jpg",             Description = "spell", Irl = "https://www.wowhead.com/spell=53376/sanctified-wrath"},
			new Spell{Id = 273, Name = "Rule of Law",                  Icon = "Rule of Law.jpg",                  Description = "spell", Irl = "https://www.wowhead.com/spell=214202/rule-of-law"},
			new Spell{Id = 274, Name = "Reclamation (PvP)",            Icon = "Reclamation (PvP).jpg",            Description = "spell", Irl = "https://www.wowhead.com/spell=415364/reclamation"},
			new Spell{Id = 275, Name = "Moment of Compassion",         Icon = "Moment of Compassion.jpg",         Description = "spell", Irl = "https://www.wowhead.com/spell=407236/moment-of-compassion"},
			new Spell{Id = 276, Name = "Glorious Dawn",                Icon = "Glorious Dawn.jpg",                Description = "spell", Irl = "https://www.wowhead.com/spell=414387/glorious-dawn"},
		};
	};
}
