// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaladinProject.Data;


#nullable disable

namespace PaladinProject.Migrations.Spellbook
{
    [DbContext(typeof(SpellbookContext))]
    partial class SpellbookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("paladinproject.models.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spell");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Crusader Strike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Judgement"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Divine Shield"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hand Of Freedom"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cleanse"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blessing Of Protection"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Divine Steed"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Shield Of Righterous"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lay Of Hands"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Flash Of Light"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
