using PaladinProject.Models;

public class SpellbookService
{
	public List<Spell> GetAllSpells()
	{
		return new List<Spell>
		{
new Spell { Id =1, Name ="Aurora", Icon = "Breaking Dawn.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=439760/aurora"},
new Spell { Id =2, Name ="Avenging Wrath", Icon = "Avenging Wrath.jpg", Description = "", Irl = "https://www.wowhead.com/spell=31884/avenging-wrath"},
new Spell { Id =3, Name ="Barricadeof Faith", Icon = "Barrier of Faith.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385726/barricade-of-faith"},
new Spell { Id =4, Name ="Barrier of Faith2", Icon = "Beacon of Faith.jpg", Description = "", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
new Spell { Id =5, Name ="Beacon of Faith", Icon = "Beacon of Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=156910/beacon-of-faith"},
new Spell { Id =6, Name ="Beacon of Light", Icon = "Lightbearer.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=53563/beacon-of-light"},
new Spell { Id =7, Name ="Beacon of the Lightbringer", Icon = "Beacon of Virtue.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=197446/beacon-of-the-lightbringer"},
new Spell { Id =8, Name ="Beacon of Virtue3", Icon = "Blade of Vengeance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=200025/beacon-of-virtue"},
new Spell { Id =9, Name ="Blade of Vengeance2", Icon = "Blade of Justice.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403826/blade-of-vengeance"},
new Spell { Id =10, Name ="Blade of Wrath", Icon = "Blade of Wrath.jpg", Description = "", Irl = "https://www.wowhead.com/spell=231832/blade-of-wrath"},
new Spell { Id =11, Name ="Blessed Calling", Icon = "Blessed Calling.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=469770/blessed-calling"},
new Spell { Id =12, Name ="Blessed Focus2", Icon = "Blessing of Autumn.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=414289/blessed-focus"},
new Spell { Id =13, Name ="Blessing of Autumn", Icon = "Blessing of Spring.jpg", Description = "", Irl = "https://www.wowhead.com/spell=388010/blessing-of-autumn"},
new Spell { Id =14, Name ="Blessing of Spring", Icon = "Blessing of Summer.jpg", Description = "", Irl = "https://www.wowhead.com/spell=388013/blessing-of-spring"},
new Spell { Id =15, Name ="Blessing of Summer2", Icon = "Blessing of Winter.jpg", Description = "", Irl = "https://www.wowhead.com/spell=388007/blessing-of-summer"},
new Spell { Id =16, Name ="Blessing of Winter", Icon = "Boundless Salvation.jpg", Description = "", Irl = "https://www.wowhead.com/spell=388011/blessing-of-winter"},
new Spell { Id =17, Name ="Boundless Salvation2", Icon = "Commanding Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=392951/boundless-salvation"},
new Spell { Id =18, Name ="Commanding Light", Icon = "Consecration in Flame.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387781/commanding-light"},
new Spell { Id =19, Name ="Consecration in Flame", Icon = "Crusader Strike.jpg", Description = "", Irl = "https://www.wowhead.com/spell=379022/consecration-in-flame"},
new Spell { Id =20, Name ="Crusader Strike", Icon = "Crusader's Resolve.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=35395/crusader-strike"},
new Spell { Id =21, Name ="Crusader's Resolve2", Icon = "Daybreak.jpg", Description = "", Irl = "https://www.wowhead.com/spell=380188/crusaders-resolve"},
new Spell { Id =22, Name ="Daybreak3", Icon = "Divine Glimpse.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=414293/daybreak"},
new Spell { Id =23, Name ="Divine Glimpse", Icon = "Divine Inspiration.jpg", Description = "", Irl = "https://www.wowhead.com/spell=387805/divine-glimpse"},
new Spell { Id =24, Name ="Divine Inspiration", Icon = "Divine Protection.jpg", Description = "", Irl = "https://www.wowhead.com/spell=432964/divine-inspiration"},
new Spell { Id =25, Name ="Divine Protection", Icon = "Divine Reach.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=498/divine-protection"},
new Spell { Id =26, Name ="Divine Reach", Icon = "Relentless Inquisitor.jpg", Description = "", Irl = "https://www.wowhead.com/spell=469476/divine-reach"},
new Spell { Id =27, Name ="Divine Resonance2", Icon = "Divine Revelations.jpg", Description = "", Irl = "https://www.wowhead.com/spell=386738/divine-resonance"},
new Spell { Id =28, Name ="Divine Revelations", Icon = "Divine Toll.jpg", Description = "", Irl = "https://www.wowhead.com/spell=387808/divine-revelations"},
new Spell { Id =29, Name ="Divine Toll2", Icon = "Lay on Hands.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=375576/divine-toll"},
new Spell { Id =30, Name ="Empyreal Ward", Icon = "Lay on Hands.jpg", Description = "Lay on Hands grants the target 30% increased armor for 8 sec and now ignores healing reduction effects.", Irl = "https://www.wowhead.com/spell=387791/empyreal-ward"},
new Spell { Id =31, Name ="Empyrean Legacy2", Icon = "Faiths Armor.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387998/empyrean-legacy"},
new Spell { Id =32, Name ="Faith's Armor", Icon = "Ferren Marcus's Fervor.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=406101/faiths-armor"},
new Spell { Id =33, Name ="Ferren Marcus's Fervor", Icon = "First Avenger.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=378762/ferren-marcuss-fervor"},
new Spell { Id =34, Name ="First Avenger", Icon = "Flash of Light.jpg", Description = "Avenger's Shield hits 2 additional targets,  and grants you an absorb shield for 100% of all damage it deals.", Irl = "https://www.wowhead.com/spell=203776/first-avenger"},
new Spell { Id =35, Name ="Flash of Light", Icon = "Focused Enmity.jpg", Description = "", Irl = "https://www.wowhead.com/spell=19750/flash-of-light"},
new Spell { Id =36, Name ="Focused Enmity2", Icon = "Glistening Radiance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=378845/focused-enmity"},
new Spell { Id =37, Name ="Glistening Radiance2", Icon = "Glorious Dawn.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=409647/glistening-radiance"},
new Spell { Id =38, Name ="Glorious Dawn2", Icon = "Greater Judgment.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=414387/glorious-dawn"},
new Spell { Id =39, Name ="Greater Judgment2", Icon = "Holy Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
new Spell { Id =40, Name ="Holy Light2", Icon = "Holy Prism.jpg", Description = "", Irl = "https://www.wowhead.com/spell=82326/holy-light"},
new Spell { Id =41, Name ="Holy Prism2", Icon = "Holy Radiance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=114165/holy-prism"},
new Spell { Id =42, Name ="Holy Radiance", Icon = "Holy Reprieve.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=82327/holy-radiance"},
new Spell { Id =43, Name ="Holy Reprieve", Icon = "Holy Reprieve.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=469445/holy-reprieve"},
new Spell { Id =44, Name ="Holy Shock2", Icon = "Improved Ardent Defender.jpg", Description = "", Irl = "https://www.wowhead.com/spell=20473/holy-shock"},
new Spell { Id =45, Name ="Improved Ardent Defender", Icon = "Cleanse.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=393114/improved-ardent-defender"},
new Spell { Id =46, Name ="Improved Cleanse", Icon = "Cleanse.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=393024/improved-cleanse"},
new Spell { Id =47, Name ="Improved Holy Shield", Icon = "Infusion of Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=393030/improved-holy-shield"},
new Spell { Id =48, Name ="Infusion of Light2", Icon = "Inquisitor's Ire.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=53576/infusion-of-light"},
new Spell { Id =49, Name ="Inquisitor's Ire", Icon = "Inspiring Vanguard.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403975/inquisitors-ire"},
new Spell { Id =50, Name ="Inspiring Vanguard", Icon = "Judge,  Jury and Executioner.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=393022/inspiring-vanguard"},
new Spell { Id =51, Name ="Judge, Jury and Executioner", Icon = "Judgment.jpg", Description = "", Irl = "https://www.wowhead.com/spell=405607/judge-jury-and-executioner"},
new Spell { Id =52, Name ="Judgment", Icon = "Judgment of Justice.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=20271/judgment"},
new Spell { Id =53, Name ="Judgment of Justice", Icon = "Liberation.jpg", Description = "Judgment deals 10% increased damage and increases your movement speed by 10% for 5 sec.\r\n\r\nIf you have Greater Judgment, Judgment slows enemies by 30% for 8 sec.", Irl = "https://www.wowhead.com/spell=403495/judgment-of-justice"},
new Spell { Id =54, Name ="Lay on Hands2", Icon = "Light of Dawn.jpg", Description = "", Irl = "https://www.wowhead.com/spell=633/lay-on-hands"},
new Spell { Id =55, Name ="Liberation", Icon = "Light of the Martyr.jpg", Description = "", Irl = "https://www.wowhead.com/spell=461287/liberation"},
new Spell { Id =56, Name ="Light of Dawn2", Icon = "Lightforged Blessing.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=85222/light-of-dawn"},
new Spell { Id =57, Name ="Light of the Martyr", Icon = "Light's Celerity.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=183998/light-of-the-martyr"},
new Spell { Id =58, Name ="Light of the Titans", Icon = "Light's Conviction.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=378762/light-of-the-titans"},
new Spell { Id =59, Name ="Lightforged Blessing2", Icon = "Light's Countenance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =60, Name ="Light's Celerity2", Icon = "Rule of Law.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403698/lights-celerity"},
new Spell { Id =61, Name ="Light's Conviction", Icon = "Lights Hammer.jpg", Description = "", Irl = "https://www.wowhead.com/spell=414073/lights-conviction"},
new Spell { Id =62, Name ="Light's Countenance", Icon = "Lights Countenance.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=469325/lights-countenance"},
new Spell { Id =63, Name ="Light's Guidance", Icon = "Moment of Compassion.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=427445/lights-guidance"},
new Spell { Id =64, Name ="Light's Hammer", Icon = "Morning Star.jpg", Description = "", Irl = "https://www.wowhead.com/spell=114158/lights-hammer"},
new Spell { Id =65, Name ="Luminosity", Icon = "Obduracy.jpg", Description = "", Irl = "https://www.wowhead.com/spell=431402/luminosity"},
new Spell { Id =66, Name ="Moment of Compassion2", Icon = "Penitence.jpg", Description = "", Irl = "https://www.wowhead.com/spell=407236/moment-of-compassion"},
new Spell { Id =67, Name ="Morning Star", Icon = "Reclamation.jpg", Description = "", Irl = "https://www.wowhead.com/spell=431482/morning-star"},
new Spell { Id =68, Name ="Obduracy", Icon = "Obduracy.jpg", Description = "", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
new Spell { Id =69, Name ="Penitence", Icon = "Resplendent Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403026/penitence"},
new Spell { Id =70, Name ="Reclamation2", Icon = "Rush of Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=415364/reclamation"},
new Spell { Id =71, Name ="Resolute Defender", Icon = "Sacred Strength.jpg", Description = "", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
new Spell { Id =72, Name ="Resplendent Light2", Icon = "Sacrosanct Crusade.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=392902/resplendent-light"},
new Spell { Id =73, Name ="Rule of Law2", Icon = "Seal of Charity.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=214202/rule-of-law"},
new Spell { Id =74, Name ="Rush of Light", Icon = "Seal of the Crusader.jpg", Description = "", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
new Spell { Id =75, Name ="Sacred Strength", Icon = "Searing Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=469337/sacred-strength"},
new Spell { Id =76, Name ="Sacrosanct Crusade", Icon = "Shared Resolve.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=439760/aurora"},
new Spell { Id =77, Name ="Seal of Charity", Icon = "Solar Grace.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=384815/seal-of-charity"},
new Spell { Id =78, Name ="Seal of the Crusader2", Icon = "Eye for an Eye.jpg", Description = "", Irl = "https://www.wowhead.com/spell=416770/seal-of-the-crusader"},
new Spell { Id =79, Name ="Searing Light2", Icon = "Sun Sear.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=403221/searing-light"},
new Spell { Id =80, Name ="Shared Resolve", Icon = "Tirion's Devotion.jpg", Description = "", Irl = "https://www.wowhead.com/spell=432821/shared-resolve"},
new Spell { Id =81, Name ="Solar Grace", Icon = "Truth Prevails.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=431404/solar-grace"},
new Spell { Id =82, Name ="Strength in Adversity", Icon = "Tyr's Deliverance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=393071/strength-in-adversity"},
new Spell { Id =83, Name ="Sun Sear", Icon = "Sun Sear.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=431413/sun-sear"},
new Spell { Id =84, Name ="Tirion's Devotion", Icon = "Zealots Paragon.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=414720/tirions-devotion"},
new Spell { Id =85, Name ="Truth Prevails", Icon = "Adjudication.jpg", Description = "Judgment heals you for (240% of Spell power) and its mana cost is reduced by 30%. 50% of overhealing from this effect is transferred onto 2 allies within 40 yds.", Irl = "https://www.wowhead.com/spell=461273/truth-prevails"},
new Spell { Id =86, Name ="Tyr's Deliverance2", Icon = "Aegis of Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=200652/tyrs-deliverance"},
new Spell { Id =87, Name ="Unwavering Spirit", Icon = "Aegis of Protection.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=392911/unwavering-spirit"},
new Spell { Id =88, Name ="Zealot's Paragon", Icon = "Moment of Glory.jpg", Description = "", Irl = "https://www.wowhead.com/spell=391142/zealots-paragon"},
new Spell { Id =89, Name ="Adjudication", Icon = "Ardent Defender.jpg", Description = "", Irl = "https://www.wowhead.com/spell=405541/adjudication"},
new Spell { Id =90, Name ="Aegis of Light", Icon = "Ashes to Ashes.jpg", Description = "", Irl = "https://www.wowhead.com/spell=204150/aegis-of-light"},
new Spell { Id =91, Name ="Aegis of Protection", Icon = "Aura Mastery.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385515/aegis-of-protection"},
new Spell { Id =92, Name ="Afterimage", Icon = "Moment of Glory.jpg", Description = "After you spend 20 Holy Power, your next Word of Glory echoes onto a nearby ally at 30% effectiveness.", Irl = "https://www.wowhead.com/spell=385414/afterimage"},
new Spell { Id =93, Name ="Ardent Defender", Icon = "Avenging Crusader.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=31850/ardent-defender"},
new Spell { Id =94, Name ="Ashes to Ashes", Icon = "Awakening.jpg", Description = "", Irl = "https://www.wowhead.com/spell=405607/ashes-to-ashes"},
new Spell { Id =95, Name ="Aura Mastery", Icon = "Aura Mastery.jpg", Description = "", Irl = "https://www.wowhead.com/spell=31821/aura-mastery"},
new Spell { Id =96, Name ="Avenger's Shield", Icon = "Bastion of Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=31935/avengers-shield"},
new Spell { Id =97, Name ="Avenging Crusader", Icon = "Bestow Faith.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=216331/avenging-crusader"},
new Spell { Id =98, Name ="Avenging Wrath1", Icon = "Blades of Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=31884/avenging-wrath"},
new Spell { Id =99, Name ="Avenging Wrath2", Icon = "Merciful Auras.jpg", Description = "", Irl = "https://www.wowhead.com/spell=327979/avenging-wrath"},
new Spell { Id =100, Name ="Awakening", Icon = "Blessed Champion.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=248033/awakening"},
new Spell { Id =101, Name ="Awakening2", Icon = "Awakening.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=414195/awakening"},
new Spell { Id =102, Name ="Awestruck", Icon = "Awestruck.jpg", Description = "", Irl = "https://www.wowhead.com/spell=417855/awestruck"},
new Spell { Id =103, Name ="Barrier of Faith", Icon = "Barrier of Faith.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=148039/barrier-of-faith"},
new Spell { Id =104, Name ="Bastion of Light", Icon = "Bastion of Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=378974/bastion-of-light"},
new Spell { Id =105, Name ="Beacon of Light1", Icon = "Beacon of Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=53563/beacon-of-light"},
new Spell { Id =106, Name ="Beacon of Virtue", Icon = "Beacon of Virtue.jpg", Description = "", Irl = "https://www.wowhead.com/spell=200025/beacon-of-virtue"},
new Spell { Id =107, Name ="Beacon of Virtue2", Icon = "Beacon of Virtue.jpg", Description = "", Irl = "https://www.wowhead.com/spell=200025/beacon-of-virtue"},
new Spell { Id =108, Name ="Bestow Faith", Icon = "Bestow Faith.jpg", Description = "", Irl = "https://www.wowhead.com/spell=223306/bestow-faith"},
new Spell { Id =109, Name ="Blade of Justice", Icon = "Blade of Justice.jpg", Description = "", Irl = "https://www.wowhead.com/spell=184575/blade-of-justice"},
new Spell { Id =110, Name ="Blade of Justice2", Icon = "Blade of Justice.jpg", Description = "", Irl = "https://www.wowhead.com/spell=184575/blade-of-justice"},
new Spell { Id =111, Name ="Blade of Vengeance", Icon = "Blade of Justice.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403826/blade-of-vengeance"},
new Spell { Id =112, Name ="Blades of Light", Icon = "Blades of Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
new Spell { Id =113, Name ="Blessed Assurance", Icon = "Merciful Auras.jpg", Description = "", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
new Spell { Id =114, Name ="Blessed Champion", Icon = "Blessed Champion.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
new Spell { Id =115, Name ="Blessed Focus", Icon = "Blessed Focus.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=414289/blessed-focus"},
new Spell { Id =116, Name ="Blessed Hammer", Icon = "Blessed Hammer.jpg", Description = "", Irl = "https://www.wowhead.com/spell=204019/blessed-hammer"},
new Spell { Id =117, Name ="Blessed Hands", Icon = "Blessed Hands.jpg", Description = "", Irl = "https://www.wowhead.com/spell=379391/blessed-hands"},
new Spell { Id =118, Name ="Blessing of An'she", Icon = "Blessing of Anshe.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =119, Name ="Blessing of Freedom", Icon = "Blessing of Freedom.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=1044/blessing-of-freedom"},
new Spell { Id =120, Name ="Blessing of Protection", Icon = "Blessing of Protection.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=1022/blessing-of-protection"},
new Spell { Id =121, Name ="Blessing of Sacrifice", Icon = "Blessing of Sacrifice.jpg", Description = "", Irl = "https://www.wowhead.com/spell=6940/blessing-of-sacrifice"},
new Spell { Id =122, Name ="Blessing of Sacrifice2", Icon = "Blessing of Sacrifice.jpg", Description = "", Irl = "https://www.wowhead.com/spell=6940/blessing-of-sacrifice"},
new Spell { Id =123, Name ="Blessing of Spellwarding", Icon = "Blessing of Spellwarding.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=204018/blessing-of-spellwarding"},
new Spell { Id =124, Name ="Blessing of Spellwarding2", Icon = "Blessing of Spellwarding.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=204018/blessing-of-spellwarding"},
new Spell { Id =125, Name ="Blessing of Summer", Icon = "Blessing of Summer.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=388007/blessing-of-summer"},
new Spell { Id =126, Name ="Blessing of the Forge", Icon = "Final Verdict.jpg", Description = "", Irl = "https://www.wowhead.com/spell=383328/final-verdict"},
new Spell { Id =127, Name ="Blinding Light", Icon = "Blinding Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=115750/blinding-light"},
new Spell { Id =128, Name ="Boundless Salvation", Icon = "Boundless Salvation.jpg", Description = "", Irl = "https://www.wowhead.com/spell=392951/boundless-salvation"},
new Spell { Id =129, Name ="Breaking Dawn", Icon = "Breaking Dawn.jpg", Description = "", Irl = "https://www.wowhead.com/spell=409673/breaking-dawn"},
new Spell { Id =130, Name ="Bulwark of Order", Icon = "Bulwark of Order.jpg", Description = "", Irl = "https://www.wowhead.com/spell=209389/bulwark-of-order"},
new Spell { Id =131, Name ="Bulwark of Righteous Fury", Icon = "Bulwark of Righteous Fury.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385422/bulwark-of-righteous-fury"},
new Spell { Id =132, Name ="Burn to Ash", Icon = "Burn to Ash.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =133, Name ="Burning Crusade", Icon = "Burning Crusade.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=406545/burning-crusade"},
new Spell { Id =134, Name ="Burning Vengeance", Icon = "Burning Vengeance.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=406646/burning-vengeance"},
new Spell { Id =135, Name ="Cavalier", Icon = "Divine Steed.jpg", Description = "", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
new Spell { Id =136, Name ="Cleanse", Icon = "Cleanse.jpg", Description = "", Irl = "https://www.wowhead.com/spell=4987/cleanse"},
new Spell { Id =137, Name ="Cleanse Toxins", Icon = "Cleanse Toxins.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =138, Name ="Consecrated Ground", Icon = "Consecrated Ground.jpg", Description = "", Irl = "https://www.wowhead.com/spell=204054/consecrated-ground"},
new Spell { Id =139, Name ="Consecration", Icon = "Consecration.jpg", Description = "", Irl = "https://www.wowhead.com/spell=26573/consecration"},
new Spell { Id =140, Name ="Crusade", Icon = "Crusade.jpg", Description = "", Irl = "https://www.wowhead.com/spell=231895/crusade"},
new Spell { Id =141, Name ="Crusade2", Icon = "Crusade.jpg", Description = "", Irl = "https://www.wowhead.com/spell=231895/crusade"},
new Spell { Id =142, Name ="Crusader's Judgment", Icon = "Crusaders Judgment.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=204023/crusaders-judgment"},
new Spell { Id =143, Name ="Crusader's Might", Icon = "Crusaders Might.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =144, Name ="Crusader's Reprieve", Icon = "Crusader's Reprieve.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=403010/crusaders-reprieve"},
new Spell { Id =145, Name ="Crusader's Resolve", Icon = "Crusader's Resolve.jpg", Description = "", Irl = "https://www.wowhead.com/spell=380188/crusaders-resolve"},
new Spell { Id =146, Name ="Crusading Strikes", Icon = "Crusading Strikes.jpg", Description = "", Irl = "https://www.wowhead.com/spell=404542/crusading-strikes"},
new Spell { Id =147, Name ="Dawnlight", Icon = "Dawnlight.jpg", Description = "", Irl = "https://www.wowhead.com/spell=431377/dawnlight"},
new Spell { Id =148, Name ="Daybreak", Icon = "Daybreak.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=414293/daybreak"},
new Spell { Id =149, Name ="Daybreak2", Icon = "Daybreak.jpg", Description = "", Irl = "https://www.wowhead.com/spell=414293/daybreak"},
new Spell { Id =150, Name ="Divine Allegiance", Icon = "Divine Allegiance.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=406788/divine-allegiance"},
new Spell { Id =151, Name ="Divine Arbiter", Icon = "Divine Arbiter.jpg", Description = "", Irl = "https://www.wowhead.com/spell=406251/divine-arbiter"},
new Spell { Id =152, Name ="Divine Call", Icon = "Divine Call.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=403566/divine-call"},
new Spell { Id =153, Name ="Divine Guidance", Icon = "Divine Guidance.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =154, Name ="Divine Hammer", Icon = "Divine Hammer.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=198034/divine-hammer"},
new Spell { Id =155, Name ="Divine Judgement", Icon = "Divine Judgement.jpg", Description = "", Irl = "https://www.wowhead.com/spell=384820/divine-judgement"},
new Spell { Id =156, Name ="Divine Purpose", Icon = "Divine Purpose.jpg", Description = "Holy Power spending abilities have a 15% chance to make your next Holy Power spending ability free and deal 15% increased damage and healing.", Irl = "https://www.wowhead.com/spell=223819/divine-purpose"},
new Spell { Id =157, Name ="Divine Purpose2", Icon = "Divine Purpose.jpg", Description = "Holy Power spending abilities have a 10% chance to make your next Holy Power spending ability free and deal 10% increased damage and healing.", Irl = "https://www.wowhead.com/spell=408459/divine-purpose"},
new Spell { Id =158, Name ="Divine Purpose (Retribution)", Icon = "Divine Purpose (Retribution).jpg", Description = " ", Irl = "https://www.wowhead.com/spell=223819/divine-purpose"},
new Spell { Id =159, Name ="Divine Resonance", Icon = "Divine Resonance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=384027/divine-resonance"},
new Spell { Id =160, Name ="Divine Revelation", Icon = "Divine Revelation.jpg", Description = "", Irl = "https://www.wowhead.com/spell=387808/divine-revelations"},
new Spell { Id =161, Name ="Divine Shield", Icon = "Divine Shield.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=642/divine-shield"},
new Spell { Id =162, Name ="Divine Spurs", Icon = "Divine Spurs.jpg", Description = "", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
new Spell { Id =163, Name ="Divine Steed", Icon = "Divine Steed.jpg", Description = "", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
new Spell { Id =164, Name ="Divine Storm", Icon = "Divine Storm.jpg", Description = "", Irl = "https://www.wowhead.com/spell=53385/divine-storm"},
new Spell { Id =165, Name ="Divine Toll", Icon = "Divine Toll.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=375576/divine-toll"},
new Spell { Id =166, Name ="Divine Wrath", Icon = "Divine Wrath.jpg", Description = "", Irl = "https://www.wowhead.com/spell=406872/divine-wrath"},
new Spell { Id =167, Name ="Empyrean Legacy", Icon = "Lay on Hands.jpg", Description = "", Irl = "https://www.wowhead.com/spell=387998/empyrean-legacy"},
new Spell { Id =168, Name ="Empyrean Power", Icon = "Empyrean Power.jpg", Description = "", Irl = "https://www.wowhead.com/spell=286392/empyrean-power"},
new Spell { Id =169, Name ="Eternal Flame", Icon = "Eternal Flame.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=114163/eternal-flame"},
new Spell { Id =170, Name ="Execution Sentence", Icon = "Execution Sentence.jpg", Description = "", Irl = "https://www.wowhead.com/spell=343527/execution-sentence"},
new Spell { Id =171, Name ="Executioner's Will", Icon = "Executioners Will.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
new Spell { Id =172, Name ="Expurgation", Icon = "Expurgation.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=383344/expurgation"},
new Spell { Id =173, Name ="Expurgation2", Icon = "Expurgation.jpg", Description = "", Irl = "https://www.wowhead.com/spell=383344/expurgation"},
new Spell { Id =174, Name ="Eye for an Eye2", Icon = "Eye for an Eye.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=205191/eye-for-an-eye"},
new Spell { Id =175, Name ="Eye for an Eye", Icon = "Divine Arbiter.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=205191/eye-for-an-eye"},
new Spell { Id =176, Name ="Eye of Tyr", Icon = "Eye of Tyr.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =177, Name ="Faith in the Light", Icon = "Faith in the Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =178, Name ="Faith's Reward", Icon = "Faith's Reward.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385349/faiths-reward"},
new Spell { Id =179, Name ="Final Reckoning", Icon = "Final Reckoning.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=343721/final-reckoning"},
new Spell { Id =180, Name ="Final Stand", Icon = "Final Stand.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=204077/final-stand"},
new Spell { Id =181, Name ="Final Verdict", Icon = "Final Verdict.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=383328/final-verdict"},
new Spell { Id =182, Name ="Fires of Justice", Icon = "Fires of Justice.jpg", Description = "", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
new Spell { Id =183, Name ="Fist of Justice", Icon = "Fist of Justice.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=234299/fist-of-justice"},
new Spell { Id =184, Name ="Focused Enmity", Icon = "Divine Inspiration.jpg", Description = "", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
new Spell { Id =185, Name ="For Whom the Bell Tolls", Icon = "Hammer of the Righteous.jpg", Description = "Divine Toll grants up to 100% increased damage to your next 3 Judgment when striking only 1 enemy. This amount is reduced by 20% for each additional target struck.", Irl = "https://www.wowhead.com/spell=53595/hammer-of-the-righteous"},
new Spell { Id =186, Name ="Gift of the Golden Val'kyr", Icon = "Gift of the Golden Valkyr.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=407311/gift-of-the-golden-valkyr"},
new Spell { Id =187, Name ="Glimmer of Light", Icon = "Shining Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=287269/glimmer-of-light"},
new Spell { Id =188, Name ="Glistening Radiance", Icon = "Glistening Radiance.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=409647/glistening-radiance"},
new Spell { Id =189, Name ="Glorious Dawn", Icon = "Suns Avatar.jpg", Description = "", Irl = "https://www.wowhead.com/spell=414387/glorious-dawn"},
new Spell { Id =190, Name ="Golden Path", Icon = "Golden Path.jpg", Description = "", Irl = "https://www.wowhead.com/spell=386916/golden-path"},
new Spell { Id =191, Name ="Golden Path (Prot)", Icon = "Golden Path (Prot).jpg", Description = "", Irl = "https://www.wowhead.com/spell=386916/golden-path"},
new Spell { Id =192, Name ="Grand Crusader", Icon = "Grand Crusader.jpg", Description = "", Irl = "https://www.wowhead.com/spell=85043/grand-crusader"},
new Spell { Id =193, Name ="Greater Judgment", Icon = "Judgment.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
new Spell { Id =194, Name ="Guardian of Ancient Kings", Icon = "Guardian of Ancient Kings.jpg", Description = "", Irl = "https://www.wowhead.com/spell=86659/guardian-of-ancient-kings"},
new Spell { Id =195, Name ="Hammer and Anvil", Icon = "Hammer and Anvil.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =196, Name ="Hammer of Justice", Icon = "Hammer of Justice.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=853/hammer-of-justice"},
new Spell { Id =197, Name ="Hammer of the Righteous", Icon = "Hammer of the Righteous.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=53595/hammer-of-the-righteous"},
new Spell { Id =198, Name ="Hammer of Wrath", Icon = "Hammer of Wrath.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=24275/hammer-of-wrath"},
new Spell { Id =199, Name ="Hammerfall", Icon = "Crusaders Judgment.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =200, Name ="Hand of Divinity", Icon = "Hand of Divinity.jpg", Description = "", Irl = "https://www.wowhead.com/spell=414273/hand-of-divinity"},
new Spell { Id =201, Name ="Hand of the Protector", Icon = "Power of the Silver Hand.jpg", Description = "", Irl = "https://www.wowhead.com/spell=315341/hand-of-the-protector"},
new Spell { Id =202, Name ="Healing Hands", Icon = "Healing Hands.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =203, Name ="Highlord's Judgment", Icon = "Highlord's Judgment.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=405757/highlords-judgment"},
new Spell { Id =204, Name ="Highlord's Wrath", Icon = "Highlord's Wrath.jpg", Description = "", Irl = "https://www.wowhead.com/spell=405779/highlords-wrath"},
new Spell { Id =205, Name ="Holy Aegis", Icon = "Holy Aegis.jpg", Description = "", Irl = "https://www.wowhead.com/spell=379008/holy-aegis"},
new Spell { Id =206, Name ="Holy Avenger", Icon = "Suns Avatar.jpg", Description = "", Irl = "https://www.wowhead.com/spell=321136/shining-light"},
new Spell { Id =207, Name ="Holy Blade", Icon = "Holy Blade.jpg", Description = "", Irl = "https://www.wowhead.com/spell=406158/holy-blade"},
new Spell { Id =208, Name ="Holy Bulwark", Icon = "Holy Bulwark.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=432459/holy-bulwark"},
new Spell { Id =209, Name ="Holy Flames", Icon = "Holy Flames.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =210, Name ="Holy Light", Icon = "Holy Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=82326/holy-light"},
new Spell { Id =211, Name ="Holy Prism", Icon = "Holy Prism.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=114165/holy-prism"},
new Spell { Id =212, Name ="Holy Ritual", Icon = "Holy Ritual.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
new Spell { Id =213, Name ="Holy Shield", Icon = "Holy Shield.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=152261/holy-shield"},
new Spell { Id =214, Name ="Holy Shock", Icon = "Holy Shock.jpg", Description = "", Irl = "https://www.wowhead.com/spell=20473/holy-shock"},
new Spell { Id =215, Name ="Improved Blessing of Protection", Icon = "Blessing of Protection.jpg", Description = "", Irl = "https://www.wowhead.com/spell=384909/improved-blessing-of-protection"},
new Spell { Id =216, Name ="Improved Cleanse (Ret)", Icon = "Improved Cleanse (Ret).jpg", Description = " ", Irl = "https://www.wowhead.com/spell=393024/improved-cleanse"},
new Spell { Id =217, Name ="Incandescence", Icon = "Incandescence.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385639/incandescence"},
new Spell { Id =218, Name ="Inflorescence of the Sunwell", Icon = "Inflorescence of the Sunwell.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =219, Name ="Infusion of Light", Icon = "Infusion of Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=53576/infusion-of-light"},
new Spell { Id =220, Name ="Judgment of Light", Icon = "Judgment of Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=183778/judgment-of-light"},
new Spell { Id =221, Name ="Judgment of the Light", Icon = "Judgment of the Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=183778/judgment-of-the-light"},
new Spell { Id =222, Name ="Justicar's Vengeance", Icon = "Justicars Vengeance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=215661/justicars-vengeance"},
new Spell { Id =223, Name ="Lay on Hands", Icon = "Lay on Hands.jpg", Description = "", Irl = "https://www.wowhead.com/spell=633/lay-on-hands"},
new Spell { Id =224, Name ="Lead the Charge", Icon = "Lead the Charge.jpg", Description = "", Irl = "https://www.wowhead.com/spell=321136/shining-light"},
new Spell { Id =225, Name ="Light of Dawn", Icon = "Light of Dawn.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=85222/light-of-dawn"},
new Spell { Id =226, Name ="Light of the Protector", Icon = "Light of the Protector.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=184092/light-of-the-protector"},
new Spell { Id =227, Name ="Lightbearer", Icon = "Lightbearer.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =228, Name ="Lightbringer's Radiance", Icon = "Lightbringer's Radiance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=405767/lightbringers-radiance"},
new Spell { Id =229, Name ="Lightforged Blessing", Icon = "Lightforged Blessing.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =230, Name ="Light's Celerity", Icon = "Light's Celerity.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=403698/lights-celerity"},
new Spell { Id =231, Name ="Light's Deliverance", Icon = "Lights Deliverance.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =232, Name ="Light's Revocation", Icon = "Divine Shield.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =233, Name ="Merciful Auras", Icon = "Merciful Auras.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385414/merciful-auras"},
new Spell { Id =234, Name ="Moment of Compassion", Icon = "Moment of Compassion.jpg", Description = "Your Flash of Light heals for an additional 50% when cast on a target affected by your Beacon of Light.", Irl = "https://www.wowhead.com/spell=407236/moment-of-compassion"},
new Spell { Id =235, Name ="Moment of Glory", Icon = "Moment of Glory.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =236, Name ="Of Dusk and Dawn", Icon = "Light of Dawn.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385125/of-dusk-and-dawn"},
new Spell { Id =237, Name ="Overflowing Light", Icon = "Overflowing Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=461244/overflowing-light"},
new Spell { Id =238, Name ="Power of the Silver Hand", Icon = "Power of the Silver Hand.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=200294/power-of-the-silver-hand"},
new Spell { Id =239, Name ="Punishment", Icon = "Rebuke.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403537/punishment"},
new Spell { Id =240, Name ="Radiant Glory", Icon = "Radiant Glory.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=405757/radiant-glory"},
new Spell { Id =241, Name ="Rebuke", Icon = "Rebuke.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=96231/rebuke"},
new Spell { Id =242, Name ="Reclamation", Icon = "Rule of Law.jpg", Description = " Holy Shock and Crusader Strike refund up to 10% of their Mana cost and deal up to 50% more healing or damage,  based on the target's missing health.", Irl = "https://www.wowhead.com/spell=415364/reclamation"},
new Spell { Id =243, Name ="Reclamation (PvP)", Icon = "Reclamation (PvP).jpg", Description = "", Irl = "https://www.wowhead.com/spell=415364/reclamation"},
new Spell { Id =244, Name ="Recompense", Icon = "Recompense.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385427/recompense"},
new Spell { Id =245, Name ="Redoubt", Icon = "Redoubt.jpg", Description = "", Irl = "https://www.wowhead.com/spell=280373/redoubt"},
new Spell { Id =246, Name ="Relentless Inquisitor", Icon = "Relentless Inquisitor.jpg", Description = "", Irl = "https://www.wowhead.com/spell=376996/relentless-inquisitor"},
new Spell { Id =247, Name ="Repentance", Icon = "Repentance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=20066/repentance"},
new Spell { Id =248, Name ="Resplendent Light", Icon = "Resplendent Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=392902/resplendent-light"},
new Spell { Id =249, Name ="Resplendent Light (Ret)", Icon = "Resplendent Light (Ret).jpg", Description = "", Irl = "https://www.wowhead.com/spell=383254/resplendent-light"},
new Spell { Id =250, Name ="Righteous Cause", Icon = "Righteous Cause.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=405686/righteous-cause"},
new Spell { Id =251, Name ="Righteous Judgment", Icon = "Shake the Heavens.jpg", Description = "", Irl = "https://www.wowhead.com/spell=190784/divine-steed"},
new Spell { Id =252, Name ="Righteous Protector", Icon = "Shield of Vengeance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =253, Name ="Righteous Verdict", Icon = "Final Verdict.jpg", Description = "", Irl = "https://www.wowhead.com/spell=267610/righteous-verdict"},
new Spell { Id =254, Name ="Rising Sunlight", Icon = "Rising Sunlight.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =255, Name ="Rite of Sanctification", Icon = "Rite of Sanctification.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =256, Name ="Rule of Law", Icon = "Rule of Law.jpg", Description = "", Irl = "https://www.wowhead.com/spell=214202/rule-of-law"},
new Spell { Id =257, Name ="Sacrifice of the Just", Icon = "Blessing of Sacrifice.jpg", Description = "", Irl = "https://www.wowhead.com/spell=384820/divine-judgement"},
new Spell { Id =258, Name ="Sanctified Ground (Ret)", Icon = "Sanctified Ground (Ret).jpg", Description = "", Irl = "https://www.wowhead.com/spell=204054/sanctified-ground"},
new Spell { Id =259, Name ="Sanctified Plates", Icon = "Sanctified Plates.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=394081/sanctified-plates"},
new Spell { Id =260, Name ="Sanctified Plates2", Icon = "Sanctified Wrath.jpg", Description = "", Irl = "https://www.wowhead.com/spell=53376/sanctified-wrath"},
new Spell { Id =261, Name ="Sanctified Plates3", Icon = "Sanctified Wrath.jpg", Description = "", Irl = "https://www.wowhead.com/spell=53376/sanctified-wrath"},
new Spell { Id =262, Name ="Sanctified Wrath", Icon = "Sanctified Wrath.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=53376/sanctified-wrath"},
new Spell { Id =263, Name ="Saved by the Light", Icon = "Saved by the Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=321136/shining-light"},
new Spell { Id =264, Name ="Seal of Clarity", Icon = "Seal of Clarity.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385428/seal-of-clarity"},
new Spell { Id =265, Name ="Seal of Clarity2", Icon = "Seal of Clarity.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385428/seal-of-clarity"},
new Spell { Id =266, Name ="Seal of Mercy", Icon = "Seal of Mercy.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385427/seal-of-mercy"},
new Spell { Id =267, Name ="Seal of Mercy2", Icon = "Seal of Mercy.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385427/seal-of-mercy"},
new Spell { Id =268, Name ="Seal of Mercy (Ret)", Icon = "Seal of Mercy (Ret).jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385427/seal-of-mercy"},
new Spell { Id =269, Name ="Seal of Might", Icon = "Seal of Might.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385450/seal-of-might"},
new Spell { Id =270, Name ="Seal of Order", Icon = "Seal of Order.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385425/seal-of-order"},
new Spell { Id =271, Name ="Seal of Order2", Icon = "Seal of Order.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385425/seal-of-order"},
new Spell { Id =272, Name ="Seal of the Crusader", Icon = "SotC.jpg", Description = "", Irl = "https://www.wowhead.com/spell=416770/seal-of-the-crusader"},
new Spell { Id =273, Name ="Seal of Wrath", Icon = "Seal of Wrath.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=405798/seal-of-wrath"},
new Spell { Id =274, Name ="Sealed Verdict", Icon = "Sealed Verdict.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385633/sealed-verdict"},
new Spell { Id =275, Name ="Searing Judgment", Icon = "Searing Judgment.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403530/searing-judgment"},
new Spell { Id =276, Name ="Searing Light", Icon = "Searing Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=403221/searing-light"},
new Spell { Id =277, Name ="Seething Flames", Icon = "Seething Flames.jpg", Description = "", Irl = "https://www.wowhead.com/spell=384820/divine-judgement"},
new Spell { Id =278, Name ="Selfless Healer", Icon = "Selfless Healer.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =279, Name ="Sentinel", Icon = "Sentinel.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =280, Name ="Seraphim", Icon = "Seraphim.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=152262/seraphim"},
new Spell { Id =281, Name ="Shake the Heavens", Icon = "Shake the Heavens.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=403509/shake-the-heavens"},
new Spell { Id =282, Name ="Shield of the Righteous", Icon = "Shield of the Righteous.jpg", Description = "", Irl = "https://www.wowhead.com/spell=53600/shield-of-the-righteous"},
new Spell { Id =283, Name ="Shield of Vengeance", Icon = "Shield of Vengeance.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=184662/shield-of-vengeance"},
new Spell { Id =284, Name ="Shielding Words", Icon = "Shielding Words.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=379010/shielding-words"},
new Spell { Id =285, Name ="Shining Light", Icon = "Shining Light.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=327510/shining-light"},
new Spell { Id =286, Name ="Stoicism", Icon = "Stoicism.jpg", Description = "", Irl = "https://www.wowhead.com/spell=384820/divine-judgement"},
new Spell { Id =287, Name ="Sun's Avatar", Icon = "Suns Avatar.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =288, Name ="Templar Slash", Icon = "Templar Slash.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=407479/templar-slash"},
new Spell { Id =289, Name ="Templar Strike", Icon = "Templar Strike.jpg", Description = "", Irl = "https://www.wowhead.com/spell=407480/templar-strike"},
new Spell { Id =290, Name ="Templar Strikes", Icon = "Templar Strikes.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=407480/templar-strikes"},
new Spell { Id =291, Name ="Templar's Verdict", Icon = "Templar's Verdict.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=85256/templars-verdict"},
new Spell { Id =292, Name ="Touch of Light", Icon = "Touch of Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=386922/touch-of-light"},
new Spell { Id =293, Name ="Tower of Radiance", Icon = "Executioners Will.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=385639/greater-judgment"},
new Spell { Id =294, Name ="Truth's Wake", Icon = "Truth's Wake.jpg", Description = "", Irl = "https://www.wowhead.com/spell=406154/truths-wake"},
new Spell { Id =295, Name ="Truth's Wake2", Icon = "Truth's Wake.jpg", Description = "", Irl = "https://www.wowhead.com/spell=406154/truths-wake"},
new Spell { Id =296, Name ="Turn Evil", Icon = "Turn Evil.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =297, Name ="Tyr's Deliverance", Icon = "Tyrs Deliverance.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=200652/tyrs-deliverance"},
new Spell { Id =298, Name ="Tyr's Deliverance (PvP)", Icon = "Tyr's Deliverance (PvP).jpg", Description = " ", Irl = "https://www.wowhead.com/spell=199454/tyrs-deliverance"},
new Spell { Id =299, Name ="Tyr's Enforcer", Icon = "Tyr's Enforcer.jpg", Description = "", Irl = "https://www.wowhead.com/spell=406570/tyrs-enforcer"},
new Spell { Id =300, Name ="Unbound Freedom", Icon = "Blessing of Freedom.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=387174/eye-of-tyr"},
new Spell { Id =301, Name ="Unbreakable Spirit", Icon = "Unbreakable Spirit.jpg", Description = "", Irl = "https://www.wowhead.com/spell=114154/unbreakable-spirit"},
new Spell { Id =302, Name ="Undisputed Ruling", Icon = "Greater Judgement.jpg", Description = "", Irl = "https://www.wowhead.com/spell=384820/divine-judgement"},
new Spell { Id =303, Name ="Unending Light", Icon = "Unending Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=405719/unending-light"},
new Spell { Id =304, Name ="Unrelenting Charger", Icon = "Unrelenting Charger.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =305, Name ="Vanguard's Momentum", Icon = "Vanguard's Momentum.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=405065/vanguards-momentum"},
new Spell { Id =306, Name ="Veneration", Icon = "Veneration.jpg", Description = "", Irl = "https://www.wowhead.com/spell=392902/veneration"},
new Spell { Id =307, Name ="Vengeful Wrath", Icon = "Hammer of Wrath.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403592/vengeful-wrath"},
new Spell { Id =308, Name ="Wake of Ashes", Icon = "Wake of Ashes.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=255937/wake-of-ashes"},
new Spell { Id =309, Name ="Wrathful Descent", Icon = "Wrathful Descent.jpg", Description = "", Irl = "https://www.wowhead.com/spell=403479/lightforged-blessing"},
new Spell { Id =310, Name ="Zeal", Icon = "Zeal.jpg", Description = " ", Irl = "https://www.wowhead.com/spell=269569/zeal"},
new Spell { Id =311, Name ="Zealous Vindication", Icon = "Zealous Vindication.jpg", Description = "Hammer of Light instantly calls down 2 Empyrean Hammers on your target when it is cast.", Irl = "https://www.wowhead.com/spell=431463/zealous-vindication"},

new Spell { Id =312, Name ="Gleaming Rays", Icon = "Gleaming Rays.jpg", Description = "", Irl = "https://www.wowhead.com/spell=431480/gleaming-rays"},
new Spell { Id =313, Name ="Will of the Dawn", Icon = "Judgment of Light.jpg", Description = "", Irl = "https://www.wowhead.com/spell=431462/will-of-the-dawn"},
new Spell { Id =314, Name ="Second Sunrise", Icon = "Divine Guidance.jpg", Description = "", Irl = "https://www.wowhead.com/spell=200482/second-sunrise"},
new Spell { Id =315, Name ="Quickened Invocation", Icon = "Bulwark of Order.jpg", Description = "", Irl = "https://www.wowhead.com/spell=379391/quickened-invocation"},
new Spell { Id =316, Name ="Extrication", Icon = "Extrication.jpg", Description = "", Irl = "https://www.wowhead.com/spell=461278/extrication"},
new Spell { Id =317, Name ="Protection of Tyr", Icon = "Aura Mastery.jpg", Description = "Aura Mastery also increases all healing received by party or raid members within 40 yards by 10%.", Irl = "https://www.wowhead.com/spell=200430/protection-of-tyr"},
new Spell { Id =318, Name ="A Just Reward", Icon = "A Just Reward.jpg", Description = "", Irl = "https://www.wowhead.com/spell=469411/a-just-reward"},
new Spell { Id =320, Name ="Auras of the Resolute", Icon = "Devotion Aura.jpg", Description = "", Irl = "https://www.wowhead.com/spell=385633/auras-of-the-resolute"},
new Spell { Id =321, Name ="Devotion Aura", Icon = "Devotion Aura", Description = "", Irl = "https://www.wowhead.com/spell=465/devotion-aura"},
new Spell { Id =322, Name ="Inspired Guard", Icon = "Divine Protection.jpg", Description = "", Irl = "https://www.wowhead.com/spell=469439/inspired-guard"},

		};
	}
}
